language: emacs-lisp
before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy emacs25-nox emacs25-el
script:
  - make test EMACS=emacs-25.3
notifications:
  email: false
